### PR TITLE
Moved other README files except the main one into a separate director…

### PR DESCRIPTION
**Pull request by Gokul2003g**
Moved README*.md to the folder README except the file README.md

### CODE REVIEW

**Comment by BaseMax** [comment]
Thank you so much for your PR.
@jbampton will review it.

**Review by jbampton — CHANGES_REQUESTED** [review]
`README_DOCKER.md` should stay in the root folder.

**Review by jbampton — CHANGES_REQUESTED** [review]
Language links need to work as well

**Comment by jbampton** [comment]
Basically all non-English Markdown files should be moved.

**Comment by Gokul2003g** [comment]
So should I delete all other README files except README.md and README_DOCKER.md

**Comment by jbampton** [comment]
Probably best to call the subfolder `langs`  short for languages.

So in future we may be able to translate the mission statement or docker file

**Comment by jbampton** [comment]
You should not delete any files just move them

**Review by Gokul2003g — COMMENTED** [review]
Are the following changes OK. And can you please tell me about the Language links.

**Comment by jbampton** [comment]
These links need to work on each page:

Screen Shot 2022-09-03 at 2 39 11 am

**Comment by Gokul2003g** [comment]
Language links are now working proper.

**Comment by jbampton** [comment]
So now just the "English" link on the non-English README need fixing

**Review by jbampton — APPROVED** [review]

**Pull request merged**
