### PR TITLE
Fixes text overlapping checkbox in Arabic

### LINKED ISSUE #149: 🥊 🍱 Checkbox direction problem at AR.md file ✔️✅

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #149

### CODE REVIEW

**Review by abdorah — COMMENTED** [review]
Thank you @mohitsaxenaknoldus I see that you solved the issue:
image
but can you please re-run the pre-commit?

**Comment by mohitsaxenaknoldus** [comment]
> Thank you @mohitsaxenaknoldus I see that you solved the issue:
> image
> but can you please re-run the pre-commit?

How can I do that?

**Comment by abdorah** [comment]
check the contributing.md file you will find this paragraph:
>If you have Python at your system, so you can easily install pre-commit via pip install pre-commit.

>It's usually a good idea to run the hooks against all the files when adding new hooks (usually pre-commit will only run on the changed files during git hooks). Use pre-commit run --all-files to check all files.

>To run a single hook use pre-commit run --all-files <hook_id>

>To update use pre-commit autoupdate

**Comment by mohitsaxenaknoldus** [comment]
I tried that but clang-format failed. I don't know how i didn't change anything else. The build was passing the last time i raised a PR.

```
Format files with Clang Format...........................................Failed
- hook id: clang-format
- exit code: 1
- files were modified by this hook

src/parser/lexer/main.c
====================
---
>       if (argc == 1)


<       if (argc == 1) {
---
>       {
>       }
>       else if (argc == 2)


<       } else if (argc == 2) {
---
>       {
>       }
>       else if (argc == 3)


<       } else if (argc == 3) {
---
>       {
>       while (!peekFor(TOKEN_EOF))


<       while(!peekFor(TOKEN_EOF)) {
---
>       {
src/parser/lexer/token.c
====================
---
>  // printf(YELLOW "Token Debug: " format " at %d on %s in %s" \


<        // printf(YELLOW "Token Debug: " format " at %d on %s in %s" \
---
>  // #define debug_token(format, args...)


<        // #define debug_token(format, args...)
src/parser/lexer/lexer.c
====================
---
>  // printf(CYAN "Lexer Debug: " format " at %d on %s in %s" \


<        // printf(CYAN "Lexer Debug: " format " at %d on %s in %s" \
---
>  // #define debug_lexer(format, args...)


<        // #define debug_lexer(format, args...)
---
>  #define debug_lexer(format, args...)


<  #define debug_lexer(format,args...)
---
>  void advance()


<  void advance() {
---
>  {
>  bool peekFor(TokenType t)


<  bool peekFor(TokenType t) {
---
>  {

```

**Review by BaseMax — APPROVED** [review]
Thanks

**Comment by jbampton** [comment]
Thank you everyone !!!

**Pull request merged**
