### PR TITLE
Add pre-commit to GitHub Actions

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by jbampton** [comment]
Ok maybe you need to enable actions ?

**Comment by BaseMax** [comment]
Hi John, sorry here electric power ⚡ is off, so I have not access to PC and
now I'm see your message via phone.
Sorry about that.

If possible, please you check it.

**Comment by BaseMax** [comment]
HI, The pre-commit is ready?

**Comment by jbampton** [comment]
Yes.  My power just went off.

**Pull request merged**
