### PR TITLE
C güncelle 

### PR DESCRIPTION
**Pull request by devkadirselcuk**

### CODE REVIEW

**Comment by BaseMax** [comment]
https://docs.mergify.io/configuration/

mergify.io seems nice.

Similar config files:
- https://github.com/Mergifyio/mergify-engine/blob/main/.mergify.yml
- https://github.com/rook/rook/blob/master/.mergify.yml

**Review by jbampton — CHANGES_REQUESTED** [review]
Clang Format is failing.

clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1
- files were modified by this hook

**Comment by BaseMax** [comment]
What is "güncelle "?

**Comment by jbampton** [comment]
Hey @BaseMax 

Screen Shot 2021-06-15 at 6 29 55 am

**Comment by jbampton** [comment]
Did you install `pre-commit` ?   Are you running Windows, Linux or macOS ?

https://pre-commit.com/

Lint / Run pre-commit (pull_request) Failing after 53s — Run pre-commit

https://github.com/One-Language/One/pull/167/checks?check_run_id=2824632267

**Comment by BaseMax** [comment]
THANKS, I will run pre-commit...

**Pull request merged**
