### PR TITLE
Variabalize build.sh

### LINKED ISSUE #216: Using shell variables in build.sh of the test stage
As you know it's better for example: to get `clang` from  the **CC** variable.
and not repeat other arguments and flags.
We can put requirements file paths into a variable to make the build.sh, file shorter.

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #216

### CODE REVIEW

**Comment by BaseMax** [comment]
Thanks, Please move `clang` to a variable.
such as:
```
CC = clang
```

After that let me know to merge this.

**Comment by mohitsaxenaknoldus** [comment]
> Thanks, Please move `clang` to a variable.
> such as:
> 
> ```
> CC = clang
> ```
> 
> After that let me know to merge this.

Moved clang to CC variable. You can merge this now.

**Comment by BaseMax** [comment]
Thanks, good job.

**Review by BaseMax — APPROVED** [review]
LGTM.

**Comment by BaseMax** [comment]
For more and more work in the future, If you want, we can be in touch with each other in Discord. (BaseMax#3529)

**Comment by mohitsaxenaknoldus** [comment]
> For more and more work in the future, If you want, we can be in touch with each other in Discord. (BaseMax#3529)

Absolutely! I will add you now.

**Pull request merged**
