### PR TITLE
Added markdown-link-check to pre-commit #463

### LINKED ISSUE #463: Add `markdown-link-check` to `pre-commit`
Best to add `markdown-link-check` to `pre-commit` so we can test locally on `git commit`.

So we will need to remove the current GitHub Action that runs this as well.

https://github.com/tcort/markdown-link-check

refs #462

### PR DESCRIPTION
**Pull request by rrrokhtar**
### Description

Added markdown-link-check to pre-commit 

### Issue

Resolved #463

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
Looks like we already had a config file

https://github.com/One-Language/One/blob/main/mlc_config.json

**Comment by jbampton** [comment]
Yes thanks

**Review by jbampton — COMMENTED** [review]
ignorePatterns: An array of objects holding regular expressions which a link is checked against and skipped for checking in case of a match.

I think we can just use one "twitter" link ?

**Comment by rrrokhtar** [comment]
@jbampton 
Make sense, I have changed to a single entry

**Review by jbampton — APPROVED** [review]

**Pull request merged**
