### PR TITLE
Update .editorconfig add batch file entry 

### PR DESCRIPTION
**Pull request by jbampton**
Uses `crlf` for batch files

refs #300

### CODE REVIEW

**Comment by jbampton** [comment]
Yes batch files for Windows

**Comment by jbampton** [comment]
From #300

**Comment by BaseMax** [comment]
why not merged?

**Comment by BaseMax** [comment]
why not merged?

**Comment by BaseMax** [comment]
cc @jbampton

**Comment by BaseMax** [comment]
why not merged?

**Pull request merged**
